#!/usr/bin/env python

import sys
from langchain_community.llms import Ollama
import git
import pathlib
from halo import Halo

model = "tavernari/git-commit-message"
llama_url = "http://localhost:11434"
ollama = Ollama(base_url=llama_url, model=model)


def explain_diff(diff):
    content = diff
    systemPrompt = f"""    
    Only use the following information to answer the question. 
    - Do not use anything else
    - Do not use your own knowledge.
    - Do not use your own opinion.
    - Do not use anything that is not in the diff.
    - Don not use the character `"` or `'` in your answer.
    - Be as concise as possible.
    - Be as specific as possible.
    - Be as accurate as possible.
    Task: Write a git commit message for the following diff
    ```
    {content}
    ```
    """
    return ollama(systemPrompt)


repoPath = pathlib.Path(__file__).parent
spinner = Halo(text='Create git commit...', spinner='line')
spinner.start()
if repoPath.name == "hooks":
    repoPath = repoPath.parent.parent
    repo = git.Repo(repoPath)
    diff = repo.git.diff(repo.commit())
    commit_msg_filepath = sys.argv[1]
    with open(commit_msg_filepath, 'w') as f:
        f.write(explain_diff(diff))
else:
    repo = git.Repo(repoPath)
    diff = repo.git.diff(repo.commit())
    print(explain_diff(diff))
    
spinner.succeed('Processing complete!')
